[tools]
crossplane = "2.1.3"
dive = "0.13.1"
go = "1.25.5"
"go:github.com/deckrun/dockadvisor/cmd/dockadvisor" = "latest"
helm = "3.20.0"
kubectl = "1.35.0"
linkerd = "25.9.3"
node = "lts"
"npm:@zed-industries/claude-code-acp" = "latest"
"pipx:ansible-core" = "latest"
"pipx:terraform-local" = "latest"
python = "3.14.2"
terraform = "1.14.3"
terraform-docs = "0.21.0"
tflint = "0.60.0"
uv = "0.9.24"
vault = "1.21.2"

[settings]
idiomatic_version_file_enable_tools = ["python"]
